ARG JENKINS_AGENT_IMAGE_VERSION=jdk21
FROM jenkins/ssh-agent:${JENKINS_AGENT_IMAGE_VERSION}
RUN \
    apt-get update && \
    apt-get install -y lsb-release ca-certificates curl && \
    install -m 0755 -d /etc/apt/keyrings && \
    curl -fsSL https://download.docker.com/linux/debian/gpg -o /etc/apt/keyrings/docker.asc && \
    chmod a+r /etc/apt/keyrings/docker.asc && \
    echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] \
    https://download.docker.com/linux/debian $(. /etc/os-release && echo \"$VERSION_CODENAME\") stable" \
    | tee /etc/apt/sources.list.d/docker.list > /dev/null && \
    apt-get update && \
    apt-get install -y docker-ce-cli && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

ENTRYPOINT JENKINS_AGENT_SSH_PUBKEY=$(cat $JENKINS_AGENT_SSH_PUBKEY_FILE) setup-sshd
